version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  apicurio-registry-mem:
    image: apicurio/apicurio-registry-mem:2.6.13.Final
    #For prod, use apicurio/apicurio-registry-sql
    container_name: apicurio-registry-mem
    ports:
      - "8080:8080"

volumes:
  rabbitmq_data:
